baseURL = "https://francis.run/"
languageCode = "en"
title = "Francis Toh"
copyright = "© Copyright [Francis Tho](https://twitter.com/francis_run) | [Ink](https://github.com/knadh/hugo-ink) theme on [Hugo](https://gohugo.io)"
paginate = 6

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-169239941-1"
disqusShortname = "francis-run"
dataDir = "data"
contentDir= "content"

enableEmoji = true
enableGitInfo = true 
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage= true

[taxonomies]
  tags = "tags"

[params]
	subtitle = "Blog"
	description = "Software Enigneer | Co-organizer [@GDG Beijing](https://gdg.community.dev/gdg-beijing) | Technique: Java,Python,Rust,Big Data,Cloud Native,etc..."
	avatar = "https://avatars1.githubusercontent.com/u/25944814"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	favicon="img/icon.png"
	mode = "dark"
	busuanzi = true
	social_share = true
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[author]
    name = "Francis Toh"
	
# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Events"
url = "/events"
weight = 3

[[menu.main]]
name = "Album"
url = "/album"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/francis-du/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/francis-du"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/intent/follow?screen_name=francis_run"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:francis@francisdu.com"

[[params.social]]
name = "Dev.to"
icon = "link"
url = "https://dev.to/francisdu"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Site Status"
icon = "monitor"
url = "https://status.francis.run/"